<a href="https://colab.research.google.com/github/SeWonKwon/DeepLearning/blob/main/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0(TensorFlow)_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서플로우 (Tensorflow)

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/TensorFlowLogo.svg/1200px-TensorFlowLogo.svg.png" width="300">

- 가장 널리 쓰이는 딥러닝 프레임워크 중 하나

- 구글이 주도적으로 개발하는 플랫폼

- 파이썬, C++ API를 기본적으로 제공하고,  
  자바스크립트(JavaScript), 자바(Java), 고(Go), 스위프트(Swift) 등 다양한 프로그래밍 언어를 지원

- tf.keras를 중심으로 고수준 API 통합 (2.x 버전)

- TPU(Tensor Processing Unit) 지원
  - TPU는 GPU보다 전력을 적게 소모, 경제적
  
  - 일반적으로 32비트(float32)로 수행되는 곱셈 연산을 16비트(float16)로 낮춤

## 텐서플로우 아키텍쳐

<img src="https://developers.google.com/machine-learning/crash-course/images/TFHierarchy.svg">

<sub>출처: https://developers.google.com/machine-learning/crash-course/first-steps-with-tensorflow/toolkit</sub>

[이수안컴퓨터연구소 유튜브 출처](https://www.youtube.com/watch?v=B961QM47g64&t=1389s)


## 텐서플로우 시작하기

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.4.1


### 텐서(Tensor)의 객체
- 타입(Type): `string`, `float32`, `float16`, `int32`, `int8` 등

- 형상(Shape): 0, 1, 2차원 등의 데이터 차원 

- 축(Rank): 차원의 개수

### 텐서의 차원과 연산

In [ ]:
a  = tf.constant(2) # default dtype int32
print(tf.rank(a)) # 0차원
print(a)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
b = tf.constant([2,3])
print(tf.rank(b)) # 1차원
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [ ]:
c = tf.constant([[2,3],[6,7]])
print(tf.rank(c))
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [ ]:
d = tf.constant(['Hello'])
print(tf.rank(d))
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'Hello'], shape=(1,), dtype=string)


### 난수 생성

In [ ]:
rand = tf.random.uniform([1], 0, 1) # 동등한 확률 : uniform distribution
print(rand.shape)
print(tf.rank(rand))
print(rand)
rand

(1,)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([0.8434584], shape=(1,), dtype=float32)


<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8434584], dtype=float32)>

In [ ]:
rand2 = tf.random.normal([1,2], 0, 1) # 정규 분포 : normal distribution
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[ 1.1101966  -0.06488999]], shape=(1, 2), dtype=float32)


In [ ]:
rand3 = tf.random.normal(shape=(3,2), mean=0, stddev=1)
print(rand3.shape)
rand3

(3, 2)


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.76547503, -0.3435235 ],
       [-0.93831587,  1.2865462 ],
       [ 0.5784094 , -0.09580006]], dtype=float32)>

### 즉시 실행 모드 (Eager Mode) 지원
- 즉시 실행모드를 통해 텐서플로우를 파이썬처럼 사용할 수 있음

- 1.x 버전에서는 '그래프'를 생성하고, 초기화 한 뒤에 세션을 통해 **값을 흐르게 하는 작업**을 진행해야함


In [ ]:
a = tf.constant(3)
b = tf.constant(2)

In [ ]:
print(tf.add(a,b))
print(a+b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
print(tf.subtract(a,b))
print(a-b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print(tf.multiply(a,b))
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


### 텐서 플로우 ↔ 넘파이
- `numpy()`
- `tf.convet_to_tensor()`

In [ ]:
c = tf.add(a,b).numpy()
print(type(c))
c

<class 'numpy.int32'>


5

In [ ]:
c_square = np.square(c, dtype=np.float32)
c_tensor= tf.convert_to_tensor(c_square)
print(type(c_tensor))
print(c_tensor)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(25.0, shape=(), dtype=float32)


### 넘파이처럼 사용하기


In [ ]:
t = tf.constant([[1., 2., 3.],[4., 5., 6.]])
print(t.shape)
print(t.dtype)
t

(2, 3)
<dtype: 'float32'>


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
# numpy 처럼 slicing 역시 됩니다.
print(t[:,1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


### newaxis

resize 와  비슷 개념이다. 

new axis (새로 추가될 axis) 를 적어주는 곳에 생겨 나게 된다.  인덱싱을하듯이사용하면 된다.

In [ ]:
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
t[tf.newaxis,...] # t 와 비교해 보면 0번 axis에 1이 추가 된것을 볼수 있다. 

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.]]], dtype=float32)>

In [ ]:
t[:,tf.newaxis,...] # 1번 axis에 1이 추가 된것을 볼수 있다. 

<tf.Tensor: shape=(2, 1, 3), dtype=float32, numpy=
array([[[1., 2., 3.]],

       [[4., 5., 6.]]], dtype=float32)>

In [ ]:
t[...,1] # 아래는 슬라이싱과 axis 추가 까지 같이 해준것이다.

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [ ]:
t[tf.newaxis,...,1]

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[2., 5.]], dtype=float32)>

In [ ]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [ ]:
t[..., 1, tf.newaxis, tf.newaxis]

<tf.Tensor: shape=(2, 1, 1), dtype=float32, numpy=
array([[[2.]],

       [[5.]]], dtype=float32)>

In [ ]:
t[1, ..., tf.newaxis]

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [6.]], dtype=float32)>

In [ ]:
t[1, tf.newaxis]

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[4., 5., 6.]], dtype=float32)>

In [ ]:
t+10 # 텐서 플로우 에서도 broadcast 가 가능하다.

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [ ]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

### 타입 변환
- 텐서의 기본 dtype
  - float형 텐서: `float32`
  - int형 텐서: `int32`

- 연산시 텐서의 타입을 맞춰줘야 함
  - `float32` ~ `float32`
  - `int32` ~ `int32`
  - `flot32` ~ `int32` (x)

- 타입변환에는 `tf.cast()` 사용

#### int 정수형 표현
- int8 => 1비트당 2개의 숫자를 표현할 수 있으므로 8비트면 2^8 = 256개의 정수를 표현할 수 있습니다. 즉 -128에서 127까지 표현가능합니다.

- int16 => 2^16개의 정수표현 가능. -32,768에서 32,767까지.

- int32 => 2^32개의 정수표현 가능. -2,147,483,648에서 2,147,483,647까지. 

- int64 => 2^64개의 정수표현 가능. -9,223,372,036,854,775,808에서 9,223,372,036,854,775,807

#### unit 0 이상의 정수

- uint8 => 2^8개의 부호없는 정수표현 가능. 0에서 255까지. 그레이스케일 또는 3채널 컬러 이미지를 담을 때 많이 사용됩니다. 

- uint16 => 2^16개의 부호없는 정수표현 가능. 0에서 65,535까지. 

- uint32 => 2^32개의 부호없는 정수표현 가능. 0에서 4,294,967,295까지.

- uint64 => 2^64개의 부호없는 정수표현 가능. 0에서 18,446,744,073,709,551,615까지.

#### float 소수

- float16 => 1비트는 부호에, 5비트는 정수부분을 나타내는데, 10비트는 소수부분을 나타내는데 사용됩니다. 이에 대한 자세한 내용은 https://en.wikipedia.org/wiki/Single-precision_floating-point_format를 참고해주세요.^^

- float32 => 1비트 부호, 8비트 정수, 23비트 소수.

- float64 => 1비트 부호, 11비트 정수, 52비트 소수. 

#### 논리형 자료형
bool => 참(True)과 거짓(False)을 표현하기 위한 자료형입니다. 즉 uint2 겠죠.

[출처](https://bskyvision.com/736)https://bskyvision.com/736

In [ ]:
a = tf.constant(2)
print(a)

b = tf.constant(2.)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [ ]:
tf.constatnt(2.) + tf.constant(4) # data type  다르면 계산에 에러

AttributeError: ignored

In [ ]:
tf.constatnt(2.) + tf.constant(30., dtyp=tf.float64)  # default 는 float32 이기 때문에 같은 float라도 32비트와 64비트는 계산 할수 없다.

AttributeError: ignored

In [ ]:
t = tf.constant(30., dtype=tf.float64)
t2 = tf.constant(4.)

print(t2 + tf.cast(t, tf.float32))# cast method로 dtype 을 변환해서 같은 dtype으로 변환

tf.Tensor(34.0, shape=(), dtype=float32)


### AutoGraph (오토그래프)

- Tensorflow가 작업을 좀 더 빠르게 동작하게 하기 위한 방법으로 Graph로 만들어 연산을 진행

- `tf.Graph`

- 유연성이 있음

  - 모바일 애플리케이션, 임베디드 기기, 백엔드 서버와 같이 Python 인터프리터가 없는 환경에서 Tensorflow 사용 가능 

In [ ]:
import timeit

### @tf.function
- 자동으로 그래프를 생성(Auto Graph)

- 그래프로 변환하여 사용 -> GPU 연산 가능

- 파이썬으로 구성된 함수를 텐서플로우의 그래프 형태로 다루고 싶을 때 사용가능


- 원본 함수가 필요하다면 `(tf.function).python_function()`

In [ ]:
@tf.function
def my_function(x):
  return x**2 - 10*x +3

print(my_function(2))
print(my_function(tf.constant(2)))

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)


In [ ]:
def my_function2(x):
  return x**2 - 10*x +3


print(my_function2(2))
print(my_function2(tf.constant(2)))

-13
tf.Tensor(-13, shape=(), dtype=int32)


두개의 차이점은 텐서로 변환 하지 않게 된다. @tf.function 의 차이

- 이 것이 Eager mode!!


In [ ]:
tf_my_function = tf.function(my_function2) # 일반 파이썬 함수를 tf function 으로

print(tf_my_function(2))

tf.Tensor(-13, shape=(), dtype=int32)


In [ ]:
tf_my_function.python_function(2) # 일반적인 파이썬 함수로 재 변환

-13

In [ ]:
def function_to_get_faster(x, y, b):
  x = tf.matmul(x, y) # 행렬곱
  x = x + b
  return x

a_function_that_uses_a_graph = tf.function(function_to_get_faster)

x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

a_function_that_uses_a_graph(x1,y1,b1).numpy()

array([[12.]], dtype=float32)

In [ ]:
def inner_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

@tf.function
def outer_function(x):
  y = tf.constant([[2.0], [3.0]])
  b = tf.constant(4.0)
  return inner_function(x, y, b)

outer_function(tf.constant([[1.0, 2.0]])).numpy()

array([[12.]], dtype=float32)

내외부 함수를 혼합해서 사용도 가능하다.


텐서플로우가 `tf.function`으로 변환한 코드

In [ ]:
print(tf.autograph.to_code(my_function.python_function))
print(tf.autograph.to_code(tf_my_function.python_function))
print(tf.autograph.to_code(outer_function.python_function))

def tf__my_function(x):
    with ag__.FunctionScope('my_function', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = (((ag__.ld(x) ** 2) - (10 * ag__.ld(x))) + 3)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)

def tf__my_function2(x):
    with ag__.FunctionScope('my_function2', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = (((ag__.ld(x) ** 2) - (10 * ag__.ld(x))) + 3)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)

def 


 속도 향상


In [ ]:
41:24

### 변수 생성

- `tf.Variable`
- 딥러닝 모델 학습 시, 그래프 연산이 필요할 때 사용

### Autograd (자동 미분)

- `tf.GradientTape` API를 사용
- `tf.Variable` 같은 일부 입력에 대한 기울기 계산
  - 기본적으로 한번만 사용됨
- 변수가 포함된 연산만 기록

## 간단한 신경망 구조 

### 뉴런
- 입력 → 연산 → 활성화함수 → 출력

### 퍼셉트론 학습 알고리즘 (가중치 업데이트)

## $\qquad w^{(next step)} = w + \eta \ (y - \tilde{y}) \ x$

- $w \ $: 가중치

- $\eta \ $ : 학습률

- $y \ $ : 정답 레이블

- $\tilde{y} \ $: 예측 레이블


### AND Gate

### OR Gate

### XOR Gate

## 시각화 사용

### XOR Gate의 'LOSS' 시각화
